### PR TITLE
RDKE-140: Application development layer for RPi

### PR DESCRIPTION
**Pull request by leenaS-d**
Reason for change: Applictaion layer for Rpi
Test Procedure: Ensure packagegroup builds successfully
Risks: Low

### CODE REVIEW

**Review by mhughesacn — COMMENTED** [review]
Hi,
Please add some licensing files to this repo as it is already opensourced.
- LICENSE / COPYING (soft link to LICENSE) / CONTRIBUTING.md / NOTICE - look in https://github.com/rdkcentral/meta-product-raspberrypi/tree/main for these.  (Fix the year in NOTICE to 2024).
- There is one recipe here with LICENSE="CLOSED" - probably should be MIT.  An opensourced repo should not have recipes referring to CLOSED (proprietary) components.

Thank you,
Martin Hughes, RDK CMF Compliance Team

**Comment by mhughesacn** [comment]
Hi LeenaS:
Please read my comment again, about LICENSE, COPYING and NOTICE, and do as I asked.  (They were good but you have changed them again.) I will have to clear off the Blackduck vote in the tool, it will not come good by itself.
Thank you, Martin

**Comment by mhughesacn** [comment]
Thanks LeenaS: Almost there: please make COPYING a soft link to LICENSE instead of a separate file, and I will clear off the last complaint.

**Comment by arun-madhavan-013** [comment]
License, copying and notice changes are decoupled to https://github.com/rdkcentral/meta-application-development-generic/pull/4 which is blocked on BD.
Merging this to unblock development.

**Pull request merged**
